name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          attempt=1
          max_attempts=3
          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt of $max_attempts: Installing dependencies..."
            if npm ci; then
              echo "Dependencies installed successfully"
              break
            fi
            attempt=$((attempt + 1))
            if [ $attempt -le $max_attempts ]; then
              echo "Retrying in 5 seconds..."
              sleep 5
            fi
          done
          if [ $attempt -gt $max_attempts ]; then
            echo "Failed to install dependencies after $max_attempts attempts"
            exit 1
          fi
        
      - name: Run ESLint
        run: npm run lint
        
      - name: Run tests
        run: npm run test
        
      - name: Check types
        run: npm run type-check

  security-scan:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          attempt=1
          max_attempts=3
          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt of $max_attempts: Installing dependencies..."
            if npm ci; then
              echo "Dependencies installed successfully"
              break
            fi
            attempt=$((attempt + 1))
            if [ $attempt -le $max_attempts ]; then
              echo "Retrying in 5 seconds..."
              sleep 5
            fi
          done
          if [ $attempt -gt $max_attempts ]; then
            echo "Failed to install dependencies after $max_attempts attempts"
            exit 1
          fi
        
      - name: Build
        run: npm run build
        
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: dist/
